name: Main CI/CD
on: [push]
jobs:
  Build-and-Deploy-Landing-3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.2
      - name: Install packages
        run: pnpm i
      - name: Build app 🛠
        run: pnpm run build -- --source data-landing-3.js
      - name: Rsync Deployments Action
        # You may pin to the exact commit or the version.
        # uses: Burnett01/rsync-deployments@0dc935cdecc5f5e571865e60d2a6cdc673704823
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.LANDING_3_REMOTE_PATH }}
          remote_host: ${{ secrets.PRODUCTION_SERVER_IP_ADDRESS }}
          remote_user: root
          remote_key: ${{ secrets.SSH_BACH_PRIVATE_KEY }}
